main: main.c navidad.o polinomio.o
	gcc -g -Wall -o main main.c navidad.o polinomio.o

navidad.o: navidad.c navidad.h
	cc -c  -Wall navidad.c

polinomio.o: polinomio.c polinomio.h
	cc -c -Wall polinomio.c
